[package]
name = "wasm-snake"
version = "0.1.0"
edition = "2018"
author = "Cyvann"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stdweb = "0.4.20"